// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dnClTnvjNJ3stn291Sba2asknUebJSo',
    appId: '1:252844714012:web:fe094fdb26023623c9d7d9',
    messagingSenderId: '252844714012',
    projectId: 'symmetric-hash-352701',
    authDomain: 'symmetric-hash-352701.firebaseapp.com',
    databaseURL: 'https://symmetric-hash-352701-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'symmetric-hash-352701.appspot.com',
    measurementId: 'G-ZXZNXT4N1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOv3pl_f6kvYPipTDOgwmlRVQltigpbBU',
    appId: '1:252844714012:android:3ae81a716115ff7bc9d7d9',
    messagingSenderId: '252844714012',
    projectId: 'symmetric-hash-352701',
    databaseURL: 'https://symmetric-hash-352701-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'symmetric-hash-352701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHhOuryFSR7cUpQ2BcZcDUOnGI_CRfojM',
    appId: '1:252844714012:ios:6446b80fa1e957e6c9d7d9',
    messagingSenderId: '252844714012',
    projectId: 'symmetric-hash-352701',
    databaseURL: 'https://symmetric-hash-352701-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'symmetric-hash-352701.appspot.com',
    iosClientId: '252844714012-uo3ga8fda0d39p1pc1g6i21j55nmno8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHhOuryFSR7cUpQ2BcZcDUOnGI_CRfojM',
    appId: '1:252844714012:ios:6446b80fa1e957e6c9d7d9',
    messagingSenderId: '252844714012',
    projectId: 'symmetric-hash-352701',
    databaseURL: 'https://symmetric-hash-352701-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'symmetric-hash-352701.appspot.com',
    iosClientId: '252844714012-uo3ga8fda0d39p1pc1g6i21j55nmno8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
